### ISSUE TITLE
wfkafka 消费者发送group_assignment请求异常

### ISSUE THREAD

**Issue by Mengqi777** [sogou/workflow#1206]
[2023-02-27 12:00:00,002] ERROR Closing socket for xxxx:9092-xxxx:34883 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: 14 and apiVersion: 1
Caused by: org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'group_assignment': Error reading array of size 12, only 4 bytes available
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:76)
        at org.apache.kafka.common.protocol.ApiKeys.parseRequest(ApiKeys.java:149)
        at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:112)
        at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:99)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:93)
        at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:518)
        at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:511)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.network.Processor.processCompletedReceives(SocketServer.scala:511)
        at kafka.network.Processor.run(SocketServer.scala:436)
        at java.lang.Thread.run(Thread.java:750)

**Comment by Barenboim** [comment]
这个问题好像是出现rebalance时非常小概率下的互斥访问错误，而且只能在kafka server侧的log里发现，client的话这种情况下应该直接当作错误重试了。我们想办法改一下。

**Comment by Barenboim** [comment]
这个问题应该最新代码已经解决了。可以关注一下server端还有没有相关的错误。
