### ISSUE TITLE
wfkafka 消费异常导致broker一直报错

### ISSUE THREAD

**Issue by Mengqi777** [sogou/workflow#1229]
[2023-03-25 20:00:01,434] ERROR Closing socket for xxxx:9092-xxxx:46436-65487601 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: SYNC_GROUP, apiVersion: 3, connectionId: xxxx:9092-xxxx:46436-65487601, listenerName: ListenerName(PLAINTEXT), principal: User:ANONYMOUS
Caused by: java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:510)
        at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:375)
        at org.apache.kafka.common.protocol.ByteBufferAccessor.readInt(ByteBufferAccessor.java:43)
        at org.apache.kafka.common.message.SyncGroupRequestData$SyncGroupRequestAssignment.read(SyncGroupRequestData.java:692)
        at org.apache.kafka.common.message.SyncGroupRequestData$SyncGroupRequestAssignment.<init>(SyncGroupRequestData.java:648)
        at org.apache.kafka.common.message.SyncGroupRequestData.read(SyncGroupRequestData.java:240)
        at org.apache.kafka.common.message.SyncGroupRequestData.<init>(SyncGroupRequestData.java:115)
        at org.apache.kafka.common.requests.SyncGroupRequest.parse(SyncGroupRequest.java:91)
        at org.apache.kafka.common.requests.AbstractRequest.doParseRequest(AbstractRequest.java:178)
        at org.apache.kafka.common.requests.AbstractRequest.parseRequest(AbstractRequest.java:152)
        at org.apache.kafka.common.requests.RequestContext.parseRequest(RequestContext.java:95)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:102)
        at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1030)
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
        at kafka.network.Processor.run(SocketServer.scala:893)
        at java.lang.Thread.run(Thread.java:750)

**Comment by Barenboim** [comment]
什么时候开始的问题？我们最近刚刚更新了client逻辑。

**Comment by Mengqi777** [comment]
前两天出现的问题，wfkafka版本应该不是最新的

**Comment by kedixa** [comment]
fixed in #1241

**Comment by Barenboim** [comment]
问题已解决！
@Mengqi777
