### ISSUE TITLE
workflow自带的kafka客户端可能有问题，消费的时候会报版本异常，主要是consumerGroup相关

### ISSUE THREAD

**Issue by Mengqi777** [sogou/workflow#761]
这是kafka版本为0.11时的异常
[2022-02-20 09:00:00,039] ERROR Closing socket for aaaaaa:port-xxxxxxxx:56806 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: 14 and apiVersion: 1
Caused by: org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'group_assignment': Error reading field 'member_assignment': java.nio.BufferUnderflowException
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:76)
        at org.apache.kafka.common.protocol.ApiKeys.parseRequest(ApiKeys.java:149)
        at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:112)
        at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:99)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:93)
        at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:518)
        at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:511)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)

kafka2.8版本会在SYNC_GROUP时异常，导致kafka输出大量log，望修复

**Comment by wzl12356** [comment]
确认一下，0.11和2.8版本的时候，他们分别是运行一段时间报错还是启动的时候就报错？

**Comment by wzl12356** [comment]
kafka2.8 SYNC_GROUP时的错误log的内容是什么？

**Comment by wzl12356** [comment]
还有就是一共有多少个消费者，kafka的topic个数和partition的个数是什么样子的。

**Comment by Mengqi777** [comment]
2.8的log 
[2022-02-21 09:00:00,000] ERROR Closing socket for host:port-host:port-63502138 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: SYNC_GROUP, apiVersion: 3, connectionId: 10.164.43.210:9092-10.160.65.207:52091-63502138, listenerName: ListenerName(PLAINTEXT), principal: User:ANONYMOUS
Caused by: java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:509)
        at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:373)
        at org.apache.kafka.common.protocol.ByteBufferAccessor.readInt(ByteBufferAccessor.java:43)
        at org.apache.kafka.common.message.SyncGroupRequestData$SyncGroupRequestAssignment.read(SyncGroupRequestData.java:692)
        at org.apache.kafka.common.message.SyncGroupRequestData$SyncGroupRequestAssignment.<init>(SyncGroupRequestData.java:648)
        at org.apache.kafka.common.message.SyncGroupRequestData.read(SyncGroupRequestData.java:240)
        at org.apache.kafka.common.message.SyncGroupRequestData.<init>(SyncGroupRequestData.java:115)
        at org.apache.kafka.common.requests.SyncGroupRequest.parse(SyncGroupRequest.java:91)
        at org.apache.kafka.common.requests.AbstractRequest.doParseRequest(AbstractRequest.java:178)
        at org.apache.kafka.common.requests.AbstractRequest.parseRequest(AbstractRequest.java:152)
        at org.apache.kafka.common.requests.RequestContext.parseRequest(RequestContext.java:95)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:102)
        at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1030)
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
        at kafka.network.Processor.run(SocketServer.scala:893)
        at java.lang.Thread.run(Thread.java:748)

具体情况我群里说一下吧

**Comment by Mengqi777** [comment]
已解决，业务方使用不规范，一直调用leave_group
